apiVersion: v1
kind: Service
metadata:
  name: accounting-api-svc
  namespace: accounting-bot
  labels:
    app: accounting-api
spec:
  type: ClusterIP
  selector:
    app: accounting-api
  ports:
    - name: http
      port: 4000
      targetPort: 4000
