apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounting-web
  namespace: accounting-bot
  labels:
    app: accounting-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounting-web
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: accounting-web
    spec:
      containers:
        - name: accounting-web
          image: ghcr.io/destinym01/accounting-web:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
          resources:
            requests:
              memory: 32Mi
              cpu: 20m
            limits:
              memory: 64Mi
              cpu: 100m
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
