apiVersion: v1
kind: Service
metadata:
  name: accounting-web-svc
  namespace: accounting-bot
  labels:
    app: accounting-web
spec:
  type: NodePort
  selector:
    app: accounting-web
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 30300
