export const currencyFlagMapping: Record<string, string> = {
  DOP: '🇩🇴',
  USD: '🇺🇸',
  EUR: '🇪🇺',
  GBP: '🇬🇧',
  CHF: '🇨🇭',
  PLN: '🇵🇱',
  ILS: '🇮🇱',
  HUF: '🇭🇺',
  CZK: '🇨🇿',
  RON: '🇷🇴',
  BGN: '🇧🇬',
  TRY: '🇹🇷',
  CAD: '🇨🇦',
  AUD: '🇦🇺',
  DKK: '🇩🇰',
  NOK: '🇳🇴',
  SEK: '🇸🇪',
  CNY: '🇨🇳',
  AED: '🇦🇪',
};
